spring:
  application:
    name: parking
    profiles:
      active: docker
  datasource:
    url: jdbc:postgresql://db:5432/park
    driver-class-name: org.postgresql.Driver
    username: sa
    password: sa
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
  logging:
    level:
      org.hibernate.orm: WARN

springdoc:
  api-docs:
    path: /api-docs
garage:
  api:
    url: "http://localhost:3000/garage"
server:
  port: 3003